services:
  - type: web
    name: personal-finance-tracker
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start_web.sh"
    plan: free
    autoDeploy: true
